system_prompt: ''
first_message: ''
voice_settings:
  provider: 11labs
  model: nova-2
  voice_id: adam
  stability: 0.5
  similarity_boost: 0.75
  language: ru
  dynamic_fields: {}
knowledge_base_file: config/knowledge_base.txt
tools_enabled:
- web_search
- calendar_sync
